create table public.facilities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  created_at timestamptz default now()
);

insert into public.facilities (name, description)
values
(
  'Community Hall',
  'A welcoming space available for community meetings, events and activities.'
),
(
  'Community Centre',
  'A central space where Riverside community members can access support and connect with others.'
),
(
  'Recreation Area',
  'An area designed for community activities, recreation and social gatherings.'
),
(
  'Support Services',
  'Information and support designed to help community members access available resources.'
);

alter table public.facilities enable row level security;

create policy "Allow public read access to facilities"
on public.facilities
for select
to anon
using (true);