create table public.donations (
  id bigint generated by default as identity primary key,
  donor_name text not null,
  donor_email text not null,
  amount numeric(12, 2) not null,
  message text,
  status text not null default 'pending',
  created_at timestamptz default now()
);

alter table public.donations enable row level security;

create policy "Allow public donation submissions"
on public.donations
for insert
to anon
with check (
  amount > 0
);